capital(brasilia, brasil).
capital(paris, franca).
capital(londres, reino_unido).
capital(roma, italia).
capital(berlim, alemanha).
capital(madri, espanha).
capital(moscou, russia).
capital(atenas, grecia).
capital(amsterda, paises_baixos).
capital(pequim, china).
capital(toquio, japao).
capital(nova_delhi, india).
capital(seul, coreia_do_sul).
capital(bangkok, tailandia).
capital(cairo, egito).
capital(nairobi, quenia).
capital(washington_dc, estados_unidos).
capital(ottawa, canada).
capital(cidade_do_mexico, mexico).
capital(buenos_aires, argentina).
capital(lima, peru).
capital(santiago, chile).
capital(caracas, venezuela).
capital(bogota, colombia).
capital(pretoria, africa_do_sul).
capital(camberra, australia).
capital(wellington, nova_zelandia).
capital(ancara, turquia).
capital(teera, ira).
capital(jerusalem, israel).
capital(jacarta, indonesia).
capital(islamaba, paquistao).
capital(abuja, nigeria).
capital(daca, bangladesh).
capital(adis_abeba, etiopia).
capital(manila, filipinas).
capital(hanoi, vietna).
capital(kinshasa, rd_congo).
capital(dodoma, tanzania).
capital(nay_pyi_taw, mianmar).
capital(kampala, uganda).
capital(argel, argelia).
capital(cartum, sudao).
capital(kiev, ucrania).
capital(bagda, iraque).
capital(cabul, afeganistao).
capital(varsovia, polonia).
capital(rabat, marrocos).
capital(riade, arabia_saudita).
capital(tashkent, ubequistao).
capital(luanda, angola).
capital(kuala_lumpur, malasia).
capital(maputo, mocambique).
capital(acra, gana).
capital(sana, iemen).
capital(katmandu, nepal).
capital(antananarivo, madagascar).
capital(yaunde, camaroes).
capital(yamoussoukro, costa_do_marfim).
capital(pyongyang, coreia_do_norte).
capital(niamey, niger).
capital(taipei, taiwan).
capital(damasco, siria).
capital(bamako, mali).
capital(ouagadougou, burkina_faso).
capital(colombo, sri_lanka).
capital(lilongwe, malawi).
capital(lusaka, zambia).
capital(astana, cazaquistao).
capital(bucareste, romenia).
capital(quito, equador).
capital(cidade_da_guatemala, guatemala).
capital(dakar, senegal).
capital(phnom_penh, camboja).
capital(harare, zimbabue).
